### ISSUE TITLE
Moon Lord spawning

### ISSUE THREAD

**Issue by BeatACVR** [xKirtle/BuilderEssentials#6]
The Moon Lord won't spawn with a Celestial Sigil or Celestially Sigil (from fargo souls mod) while using the Builder Essentials mod. Using the celestial sigil caused the messages to appear:

Impending doom approaches...
Moon Lord has awoken!
Impending doom approaches...
Moon Lord has awoken!
Impending doom approaches...
Moon Lord has awoken!
Impending doom approaches...

When the moon lord is awoken, it despawns instantly.

Disabling this mod fixes the issue, but you can't get the build in peace item from the moon lord or use any tools from this mod.

**Comment by xKirtle** [comment]
Hi, I wasn't able to reproduce the issue on my end with these 2 mods installed, everything seems to be working.
The only possible explanation I can think of is that you or someone else already has the Build in Peace accessory equipped which automatically despawns Moon Lord as soon as it spawns. Can you provide more information? 

* What version of the mod are you running on?
* Complete mods list found in `Documents\My Games\Terraria\tModLoader\Mods\enabled.json`
* Is this happening in a dedicated server, steam host or single player?
* Have you already defeated the Golem to actually spawn Moon Lord?

**Comment by BeatACVR** [comment]
Oh, I’m an idiot. I have fargos equippable inventory mod enabled, which
equips and accessory in your inventory. I’m so sorry for wasting your time.
Thanks for response

**Comment by xKirtle** [comment]
No worries, glad it wasn't an issue with the mod itself :)
